import {AWAccelerometer} from './accelerometer';
import {AWAppManager} from './app-manager';
import {AWAuth} from './auth';
import {AWCache} from './cache';
import {AWCamera} from './camera';
import {AWCompass} from './compass';
import {AWComponent} from './component';
import {AWContacts} from './contacts';
import {AWDevice} from './device';
import {AWFileChooser} from './file-chooser';
import {AWFileTransfer} from './file-transfer';
import {AWFinder} from './finder';
import {AWHeaderBar} from './header-bar';
import {AWKeyboard} from './keyboard';
import {AWLocation} from './location';
import {AWMedia} from './media';
import {AWMediaCapture} from './media-capture';
import {AWMenu} from './menu';
import {AWNotificationManager} from './notifications';
import {AWOfflineManager} from './offline-manager';
import {AWPage} from './page';
import {AWQRReader} from './qr-reader';
import {AWSecureStorage} from './secure-storage';
import {AWVibration} from './vibration';
import {AWWebView} from './webview';

namespace AppWorksMobile {
    export const Accelerometer = AWAccelerometer;
    export const AppManager = AWAppManager;
    export const Auth = AWAuth;
    export const Cache = AWCache;
    export const Camera = AWCamera;
    export const Compass = AWCompass;
    export const Component = AWComponent;
    export const Contacts = AWContacts;
    export const Device = AWDevice;
    export const FileChooser = AWFileChooser;
    export const FileTransfer = AWFileTransfer;
    export const Finder = AWFinder;
    export const HeaderBar = AWHeaderBar;
    export const Keyboard = AWKeyboard;
    export const Location = AWLocation;
    export const Media = AWMedia;
    export const MediaCapture = AWMediaCapture;
    export const Menu = AWMenu;
    export const NotificationManager = AWNotificationManager;
    export const OfflineManager = AWOfflineManager;
    export const Page = AWPage;
    export const QRReader = AWQRReader;
    export const SecureStorage = AWSecureStorage;
    export const Vibration = AWVibration;
    export const WebView = AWWebView;
}

export = AppWorksMobile;